name: cribbage
version: 0.1.0.0
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - array
  - containers
  - criterion
  - mtl
  - QuickCheck
  - random
  - vector

library:
  source-dirs:
    - src
    - test

executables:
  cribbage-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - cribbage

tests:
  cribbage-test:
    main: Main.hs
    source-dirs: test
    dependencies:
      - cribbage

default-extensions:
  - BlockArguments
  - LambdaCase
  - NumericUnderscores
  - ScopedTypeVariables
  - TypeApplications

ghc-options:
  - -O2
