name: cribbage
version: 0.1.0.0
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - array
  - containers
  - mtl
  - random
  - vector

executables:
  cribbage:
    source-dirs: src
    main: Main.hs

default-extensions:
  - BlockArguments
  - LambdaCase
  - ScopedTypeVariables
  - TypeApplications
